### ISSUE TITLE
How to set parent task

### ISSUE THREAD

**Issue by vergissberlin** [danrspencer/jira-resource#4]
**Hi!**

thank you for that resource! I am wondering how to set the parent task with your resource.
According the Jira API documentation it should look like so:
```
      - put: jira-nr
        params:
          issue_type: Task
          summary: Build v1.0.1
          fields:
            parent: ABC-123
            description: With some text
```

but the parent task is not included in the request:

```
{
  "expand": "names,schema",
  "startAt": 0,
  "maxResults": 1,
  "total": 1,
  "issues": [
    {
      "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
      "id": "12345",
      "self": "https://jira.moo.de/rest/api/2/issue/81349",
      "key": "ABC-123",
      "fields": {
        "summary": "Build v1.0.1"
      }
    }
  ]
}
```
It allway updates the parent 
> Tue, 22 May 2018 11:07:42 GMT jira-resource Issue exists [ABC-123], updating issue ...

For the request we need something like that:

```
{"fields":
   {"parent":{"id":"10420"},
   "project":{"id":"10300"},
   "summary":"a test sub-task of my first issue",
   "issuetype":{"id":"5"},
   "description":"description"}
}
```

Any ideas?
André
